### ISSUE TITLE
Poetry install broken under Docker

### ISSUE THREAD

**Issue by AltayAkkus** [seapagan/fastapi-template#534]
**Describe the bug**
Cloning the repo, and running `docker compose up --build` fails.

**To Reproduce**
1. Clone the main branch locally
2. Run `docker compose up --build`

```
19.53   • Installing pygithub (2.1.1)
19.79 
19.79   ChefBuildError
19.79 
19.79   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
19.79   
19.79   Traceback (most recent call last):
19.79     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
19.79       main()
19.79     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
19.79       json_out['return_val'] = hook(**hook_input['kwargs'])
19.79                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19.79     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
19.79       backend = _build_backend()
19.79                 ^^^^^^^^^^^^^^^^
19.79     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
19.79       ep = os.environ['PEP517_BUILD_BACKEND']
19.79            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
19.79     File "<frozen os>", line 679, in __getitem__
19.79   KeyError: 'PEP517_BUILD_BACKEND'
19.79   
19.79 
19.79   at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:166 in _prepare
19.85       162│ 
19.85       163│                 error = ChefBuildError("\n\n".join(message_parts))
19.85       164│ 
19.85       165│             if error is not None:
19.85     → 166│                 raise error from None
19.85       167│ 
19.86       168│             return path
19.86       169│ 
19.86       170│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
19.87 
19.87 Note: This error originates from the build backend, and is likely not a problem with poetry but with jsmin (3.0.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "jsmin (==3.0.1)"'.
19.87 
19.88 
19.88   ChefBuildError
19.88 
19.88   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
19.88   
19.88   Traceback (most recent call last):
19.88     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
19.88       main()
19.88     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
19.88       json_out['return_val'] = hook(**hook_input['kwargs'])
19.88                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19.88     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
19.88       backend = _build_backend()
19.88                 ^^^^^^^^^^^^^^^^
19.88     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
19.88       ep = os.environ['PEP517_BUILD_BACKEND']
19.88            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
19.88     File "<frozen os>", line 679, in __getitem__
19.88   KeyError: 'PEP517_BUILD_BACKEND'
19.88   
19.88 
19.88   at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:166 in _prepare
19.91       162│ 
19.91       163│                 error = ChefBuildError("\n\n".join(message_parts))
19.91       164│ 
19.91       165│             if error is not None:
19.91     → 166│                 raise error from None
19.91       167│ 
19.91       168│             return path
19.91       169│ 
19.91       170│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
19.91 
19.91 Note: This error originates from the build backend, and is likely not a problem with poetry but with csscompressor (0.9.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "csscompressor (==0.9.5)"'.
19.91 
19.91   • Installing pytest (8.2.0)
19.91   • Installing python-multipart (0.0.7)
19.91   • Installing pytz (2023.3.post1)
19.97 
19.98   ChefBuildError
19.98 
19.98   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
19.98   
19.98   Traceback (most recent call last):
19.98     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
19.98       main()
19.98     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
19.98       json_out['return_val'] = hook(**hook_input['kwargs'])
19.98                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19.98     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
19.98       backend = _build_backend()
19.98                 ^^^^^^^^^^^^^^^^
19.98     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
19.98       ep = os.environ['PEP517_BUILD_BACKEND']
19.98            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
19.98     File "<frozen os>", line 679, in __getitem__
19.98   KeyError: 'PEP517_BUILD_BACKEND'
19.98   
19.98 
19.98   at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:166 in _prepare
20.02       162│ 
20.02       163│                 error = ChefBuildError("\n\n".join(message_parts))
20.03       164│ 
20.03       165│             if error is not None:
20.03     → 166│                 raise error from None
20.03       167│ 
20.03       168│             return path
20.03       169│ 
20.03       170│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
20.03 
20.03 Note: This error originates from the build backend, and is likely not a problem with poetry but with paginate (0.5.6) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "paginate (==0.5.6)"'.
20.03 
20.03   • Installing regex (2023.12.25)
20.11   • Installing simple-toml-settings (0.6.1)
20.14   • Installing single-source (0.3.0)
20.31   • Installing sqlalchemy (2.0.29)
20.32   • Installing starlette (0.37.2)
20.38   • Installing termcolor (2.4.0)
20.45   • Downgrading tomlkit (0.12.5 -> 0.12.3)
20.55   • Downgrading trove-classifiers (2024.4.10 -> 2024.1.8)
20.55   • Installing typer (0.9.4)
20.62   • Installing ujson (5.9.0)
20.71   • Installing uvicorn (0.29.0)
20.75   • Downgrading virtualenv (20.26.1 -> 20.25.0)
------
failed to solve: process "/bin/sh -c poetry install" did not complete successfully: exit code: 1
```

**Expected behavior**
Image builds successfully.

**Additional context**
This is something about the build backend, this PEP-517 build stuff is a common error (See https://github.com/python-poetry/poetry/issues/8287) but none of the fixes worked, except removing the `create.venv = false` stuff in the Dockerfile.
But then the image builds successfully, but crashes shortly (`alembic not found`)

**Comment by seapagan** [comment]
@AltayAkkus thanks for reporting this, I rarely use the docker config mself. You could probably get around temporarily by replacing the poetry stage by a simple `pip install -r requirements.txt` (or requirements-dev.txt). These are autogenerated. This would be usable for production but not really practical for a dev system.

I've seen this before and from memory it was due to some dependency (not normally the one that was mentioned). I'll take a look tonight :+1:

**Comment by seapagan** [comment]
@AltayAkkus sorry for delay. I took a look at it now and have fixed the issue in the latest HEAD.

Please take a look and see if it fixes the issue you were having. If so, I'll bump the version and release.

Thanks for the bug report :+1:

**Comment by seapagan** [comment]
going to close this now, been a few weeks and I've just tested it as working fine so I'll issue a new release today.

@AltayAkkus if you are still having issues, please reopen.
